<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $projects = [
            [
                'folio' => 1,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE TECHUMBRE Y REHABILITACION DE CANCHA DEPORTIVA',
                'project_place' => 'EJ. LA AURORA',
                'viability' => true,
            ],
            [
                'folio' => 2,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE GRADAS EN CAMPO DE BEISBOL',
                'project_place' => 'EJ. MANILA',
                'viability' => true,
            ],
            [
                'folio' => 4,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE PLAZA PUBLICA',
                'project_place' => 'EJ. GREGORIO GARCIA',
                'viability' => true,
            ],
            [
                'folio' => 5,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE CANCHA Y PLAZA',
                'project_place' => 'EJ. NUEVO BARRO',
                'viability' => true,
            ],
            [
                'folio' => 6,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE TECHUMBRE, Y REHABILITACION DE ESPACIO',
                'project_place' => 'EJ. LAS LAGARTIJAS',
                'viability' => true,
            ],
            [
                'folio' => 7,
                'assigned_district' => 12,
                'project_name' => 'CONSTRUCCION DE CANCHA',
                'project_place' => 'COL. RICARDO FLORES MAGON',
                'viability' => true,
            ],
            [
                'folio' => 10,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE CANCHA Y REHABILITACION DE PLAZA',
                'project_place' => 'EJ. EL CASTILLO',
                'viability' => true,
            ],
            [
                'folio' => 11,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE KIOSCO Y REHABILITACION DE PLAZA',
                'project_place' => 'EJ. BELLA UNION',
                'viability' => true,
            ],
            [
                'folio' => 14,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE TECHUMBRE Y REHABILITACION DE PLAZA',
                'project_place' => 'EJ. HUITRON',
                'viability' => true,
            ],
            [
                'folio' => 15,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE PLAZA Y CONSTRUCCION KIOSCO',
                'project_place' => 'EJ. ARTUTO MARTINEZ ADAME',
                'viability' => true,
            ],
            [
                'folio' => 16,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE PLAZA',
                'project_place' => 'EJ. EL TRIUNFO',
                'viability' => true,
            ],
            [
                'folio' => 18,
                'assigned_district' => 10,
                'project_name' => 'REAHBILITACION DE PLAZA Y RECONSTRUCCION DE CANCHA',
                'project_place' => 'EJ. COMPETENCIA',
                'viability' => true,
            ],
            [
                'folio' => 21,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE TECHUMRE',
                'project_place' => 'EJ. CUBA',
                'viability' => true,
            ],
            [
                'folio' => 22,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACION DE PLAZA',
                'project_place' => 'AMP. SANTA ROSA',
                'viability' => true,
            ],
            [
                'folio' => 23,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACION DE CANCHA',
                'project_place' => 'COL. LAZARO CARDENAS',
                'viability' => true,
            ],
            [
                'folio' => 25,
                'assigned_district' => 12,
                'project_name' => 'CONSTRUCCION DE TECHUMBRE Y GRADAS',
                'project_place' => 'FRACC. LA FERIA',
                'viability' => true,
            ],
            [
                'folio' => 26,
                'assigned_district' => 12,
                'project_name' => 'CONSTRUCCIÓN DE CANCHA DE FUTBOL',
                'project_place' => 'AMP. SAN ANTONIO',
                'viability' => true,
            ],
            [
                'folio' => 27,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACIÓN DE PLAZA Y CONSTRUCCIÓN DE GRADAS',
                'project_place' => '21 DE MARZO',
                'viability' => true,
            ],
            [
                'folio' => 28,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACION DE PLAZA',
                'project_place' => 'RESIDENCIAL HAMBURGO',
                'viability' => true,
            ],
            [
                'folio' => 30,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACION EN PLAZA',
                'project_place' => 'BUGAMBILIAS',
                'viability' => true,
            ],
            [
                'folio' => 31,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACIÓN DEL PARQUE',
                'project_place' => 'COL. TIERRA BLANCA',
                'viability' => true,
            ],
            [
                'folio' => 32,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACION DE CANCHA CON PASTO SINTETICO',
                'project_place' => 'SAN ANTONIO',
                'viability' => true,
            ],
            [
                'folio' => 33,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE TECHUMBRE Y REHABILITACION DE PLAZA',
                'project_place' => 'EJ. GLORIETA',
                'viability' => true,
            ],
            [
                'folio' => 34,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE TECHUMBRE Y REAHBILITACION DE CANCHA',
                'project_place' => 'NUEVO GOMEZ',
                'viability' => true,
            ],
            [
                'folio' => 35,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE DEPORTIVA',
                'project_place' => 'EJ. 6 DE OCTUBRE',
                'viability' => true,
            ],
            [
                'folio' => 36,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCCION DE SALON DE USOS MULTIPLES',
                'project_place' => 'EJ. AGRICOLA PASTOR ROUAIX',
                'viability' => true,
            ],
            [
                'folio' => 37,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACION DE PLAZA PRINCIPAL',
                'project_place' => 'FRACC. BUGAMBILIAS',
                'viability' => true,
            ],
            [
                'folio' => 38,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCCION DE SALON DE USOS MULTIPLES',
                'project_place' => 'EJ. EL PARAISO',
                'viability' => true,
            ],
            [
                'folio' => 39,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE PLAZA Y CONSTRUCCION TECHUMBRE',
                'project_place' => 'EJ. EL RETOÑO',
                'viability' => true,
            ],
            [
                'folio' => 41,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE PLAZA',
                'project_place' => 'EJ. JABONOSO',
                'viability' => true,
            ],
            [
                'folio' => 42,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE CAMPO DE BEISBOL',
                'project_place' => 'LOC. EL TRANSPORTE',
                'viability' => true,
            ],
            [
                'folio' => 43,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE TECHUMBRE Y CANCHA',
                'project_place' => 'EJ. BARRO 40',
                'viability' => true,
            ],
            [
                'folio' => 46,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACION DE PLAZA',
                'project_place' => 'COL. HAMBURGO',
                'viability' => true,
            ],
            [
                'folio' => 48,
                'assigned_district' => 12,
                'project_name' => 'CONSTRUCCIÓN DE TECHUMBRE Y REHABILITACIÓN DE PLAZA',
                'project_place' => 'FRACC. VILLA NAPOLES',
                'viability' => true,
            ],
            [
                'folio' => 50,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACION DE PLAZA',
                'project_place' => 'COL. MIGUEL DE LA MADRID',
                'viability' => true,
            ],
            [
                'folio' => 52,
                'assigned_district' => 11,
                'project_name' => 'CONSTRUCCIÓN DE ESPACIO RECREATIVO',
                'project_place' => 'FRAC. LAS CARMELITAS',
                'viability' => true,
            ],
            [
                'folio' => 54,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACION DE CAMPO DE BEISBOL',
                'project_place' => 'EJ. EL CONSUELO',
                'viability' => true,
            ],
            [
                'folio' => 55,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE PLAZA PUBLICA',
                'project_place' => 'EJ. CALIFORNIA',
                'viability' => true,
            ],
            [
                'folio' => 56,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE PLAZA PUBLICA, CANCHA Y CONSTRUCCION DE PARADEROS',
                'project_place' => 'EJ. EL VERGELITO',
                'viability' => true,
            ],
            [
                'folio' => 57,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE TECHUMBRE Y REHABILITACION DE PLAZA',
                'project_place' => 'EJ. AQUILES SERDAN',
                'viability' => true,
            ],
            [
                'folio' => 58,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE CANCHA Y REHABILITACION DE PLAZA',
                'project_place' => 'EJ. CALIFORNIA',
                'viability' => true,
            ],
            [
                'folio' => 59,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE TECHUMBRE Y REHABILITACION DE CANCHA',
                'project_place' => 'EJ. EL RECUERDO',
                'viability' => true,
            ],
            [
                'folio' => 60,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE GRADAS Y MALLAS PROTECTORAS',
                'project_place' => 'EJ. LAS HUERTAS',
                'viability' => true,
            ],
            [
                'folio' => 61,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCIÓN DE DOMO Y REHABILITACIÓN DE CANCHA',
                'project_place' => 'EJ. JOSE MARIA MORELOS Y PAVON',
                'viability' => true,
            ],
            [
                'folio' => 62,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACIÓN DE CANCHA',
                'project_place' => 'EJ. SAN ALBERTO',
                'viability' => true,
            ],
            [
                'folio' => 63,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACIÓN DE CANCHA Y CONSTRUCCION DE BANQUETA',
                'project_place' => 'EJ. JIMENEZ',
                'viability' => true,
            ],
            [
                'folio' => 64,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCIÓN DE TECHUMBRE Y GRADAS',
                'project_place' => 'EJ. EL FENIX',
                'viability' => true,
            ],
            [
                'folio' => 65,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCIÓN DE CANCHA Y REHABILITACION DE PLAZA',
                'project_place' => 'EJ. LAS PLAYAS',
                'viability' => true,
            ],
            [
                'folio' => 66,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE TECHUMBRE Y REHABILITACION DE PLAZA',
                'project_place' => 'EJ. DOLORES',
                'viability' => true,
            ],
            [
                'folio' => 67,
                'assigned_district' => 12,
                'project_name' => 'CONSTRUCCION DE TECHUMBRE Y REHABILITACION DE PLAZA',
                'project_place' => 'FRACC. SANTA RITA',
                'viability' => true,
            ],
            [
                'folio' => 68,
                'assigned_district' => 12,
                'project_name' => 'CONSTRUCCION DE TECHUMBRE Y REHABILITACION DE PLAZA',
                'project_place' => 'COL. FELIPE ANGELES',
                'viability' => true,
            ],
            [
                'folio' => 69,
                'assigned_district' => 11,
                'project_name' => 'REHABILITACIÓN DE PARQUE',
                'project_place' => 'CENTENARIO',
                'viability' => true,
            ],
            [
                'folio' => 70,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCIÓN DE TECHUMBRE Y REHABILITACIÓN DE CANCHA DE USOS MULTIPLES',
                'project_place' => 'EJ. ESMERALDA',
                'viability' => true,
            ],
            [
                'folio' => 71,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCIÓN DE TECHUMBRE DE LA PLAZA PRINCIPAL',
                'project_place' => 'EJ. EMILIANO ZAPATA',
                'viability' => true,
            ],
            [
                'folio' => 72,
                'assigned_district' => 11,
                'project_name' => 'REHABILITACION DE DIVERSAS AREAS DEL CENTRO COMUNITARIO C+50',
                'project_place' => '. COL. 15 DE DICIEMBRE',
                'viability' => true,
            ],
            [
                'folio' => 73,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACION DE  CANCHA DE FUTBOL  Y CONSTRUCCION DE BAÑOS',
                'project_place' => 'FRAC. SANTA ROSA',
                'viability' => true,
            ],
            [
                'folio' => 74,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE ESTADIO DE BEISBOL',
                'project_place' => 'EJ. SAN IGNACIO',
                'viability' => true,
            ],
            [
                'folio' => 75,
                'assigned_district' => 11,
                'project_name' => 'RECUPERACION DEL CENTRO COMUNITARIO',
                'project_place' => 'FRACC. FIDEL VELÁZQUEZ.',
                'viability' => true,
            ],
            [
                'folio' => 76,
                'assigned_district' => 11,
                'project_name' => 'GRADAS CON SOMBRA EN CAMPO #2 DE LA UNIDAD DEPORTIVA FILADELFIA',
                'project_place' => 'COL. FILADELFIA',
                'viability' => true,
            ],
            [
                'folio' => 77,
                'assigned_district' => 11,
                'project_name' => 'REHABILITACIÓN DE LA UNIDAD DEPORTIVA FILADELFIA',
                'project_place' => 'COL. FILADELFIA',
                'viability' => true,
            ],
            [
                'folio' => 78,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCIÓN DE TECHUMBRE EN  PLAZA PRINCIPAL',
                'project_place' => 'EJ. JERUSALEM',
                'viability' => true,
            ],
            [
                'folio' => 79,
                'assigned_district' => 11,
                'project_name' => 'REHABILITACIÓN DE BAÑOS EN LA UNIDAD DEPORTIVA FILADELFIA',
                'project_place' => 'COL. FILADELFIA',
                'viability' => true,
            ],
            [
                'folio' => 81,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCIÓN DE KIOSCO  Y REHABILITACION DE PLAZA',
                'project_place' => 'EJ. BERLIN',
                'viability' => true,
            ],
            [
                'folio' => 82,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCIÓN DE TECHUMBRE',
                'project_place' => 'EJ. CHIHUAHUITA NUEVO',
                'viability' => true,
            ],
            [
                'folio' => 84,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCIÓN DE KIOSCO Y REHABILITACIÓN PLAZA PRINCIPAL',
                'project_place' => 'EJ. LOS ANGELES',
                'viability' => true,
            ],
            [
                'folio' => 85,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCIÓN DE TECHUMBRE Y JUEGOS INFANTILES.',
                'project_place' => 'EJ. BUEN DÍA',
                'viability' => true,
            ],
            [
                'folio' => 86,
                'assigned_district' => 12,
                'project_name' => 'CONSTRUCCIÓN DE CANCHA DE USOS MULTIPLES Y REHABILITACIÓN DE ESPACIO.',
                'project_place' => 'COL.RINCÓN SAN ALBERTO',
                'viability' => true,
            ],
            [
                'folio' => 87,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCIÓN DE UNA PLAZA CON PERIMETRO',
                'project_place' => 'EJ. EL PROGRESO',
                'viability' => true,
            ],
            [
                'folio' => 88,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCIÓN  DE LA CANCHA DE USOS MULTIPLES',
                'project_place' => 'EJ. EL CARIÑO',
                'viability' => true,
            ],
            [
                'folio' => 89,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCIÓN DE CENTRO CULTURAL PRIMERA ETAPA',
                'project_place' => 'EJ. EL COMPAS',
                'viability' => true,
            ],
            [
                'folio' => 90,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE DEPORTIVA',
                'project_place' => 'EJ. EL COMPAS',
                'viability' => true,
            ],
            [
                'folio' => 91,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACIÓN DE CANCHA DE USOS MULTIPLES  Y PLAZA DE LA COMUNIDAD',
                'project_place' => 'EJ. EL COMPAS',
                'viability' => true,
            ],
            [
                'folio' => 92,
                'assigned_district' => 11,
                'project_name' => 'CONSTRUCCIÓN DE TECHUMBRE Y REHABILITACIÓN DE CANCHA  CONALEP',
                'project_place' => 'FRACC. FIDEL VELAZQUEZ',
                'viability' => true,
            ],
            [
                'folio' => 93,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCIÓN DE CANCHA DE USOS MULTIPLES',
                'project_place' => 'EJ. JIMENEZ',
                'viability' => true,
            ],
            [
                'folio' => 94,
                'assigned_district' => 11,
                'project_name' => 'INSTALACION DE PASTO SINTECTICO EN EL  CAMPO DE BEISBOL INFANTIL',
                'project_place' => 'COL. FILADELFIA',
                'viability' => true,
            ],
            [
                'folio' => 95,
                'assigned_district' => 11,
                'project_name' => 'REMODELACION DEL GIMNASIO DE BOX',
                'project_place' => 'COL. FILADELFIA',
                'viability' => true,
            ],
            [
                'folio' => 96,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE CANCHA Y REHABILITACION DE PLAZA',
                'project_place' => 'EJ. LA TORREÑA',
                'viability' => true,
            ],
            [
                'folio' => 98,
                'assigned_district' => 11,
                'project_name' => 'INSTALACION DE PASTO SINTETICO EN CAMPO DE BEISBOL INFANTIL',
                'project_place' => 'COL. FILADELFIA',
                'viability' => true,
            ],
            [
                'folio' => 99,
                'assigned_district' => 12,
                'project_name' => 'PASILLO CULTURAL ALVARADO',
                'project_place' => 'COL FLORES MAGÓN',
                'viability' => true,
            ],
            [
                'folio' => 100,
                'assigned_district' => 12,
                'project_name' => 'BOMBAS DE CALENTADOR PARA LA ALBERCA',
                'project_place' => 'BLVD. SAN ANOTNIO',
                'viability' => true,
            ],
            [
                'folio' => 101,
                'assigned_district' => 12,
                'project_name' => 'INSTALACION DE PASTO SINTETICO EN CANCHA DE FUTBOL 7',
                'project_place' => 'BLVD. SAN ANOTNIO',
                'viability' => true,
            ],
            [
                'folio' => 102,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE TECHUMBRE',
                'project_place' => 'EJ. AMERICA UNO (LAS AMERICAS)',
                'viability' => true,
            ],
            [
                'folio' => 103,
                'assigned_district' => 11,
                'project_name' => 'REHABILITACION DE CANCHAS',
                'project_place' => 'CALZADA NOGALERAS',
                'viability' => true,
            ],
            [
                'folio' => 104,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE TECHUMBRE Y REHABILITACION DE PLAZA',
                'project_place' => 'EJ. LAS POANAS',
                'viability' => true,
            ],
            [
                'folio' => 105,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACION DE CANCHA Y PARQUE',
                'project_place' => 'COL. MIGUEL HIDALGO',
                'viability' => true,
            ],
            [
                'folio' => 106,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE CENTRO COMUNITARIO',
                'project_place' => 'EJ. PALO BLANCO',
                'viability' => true,
            ],
            [
                'folio' => 107,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACION DE ESCUELA PRIMARIA JOSE SANTOS VALDES',
                'project_place' => 'COL.SAN ALBERTO',
                'viability' => true,
            ],
            [
                'folio' => 108,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE SALON DE USOS MULTIPLES',
                'project_place' => 'LOC. ARCINAS',
                'viability' => true,
            ],
            [
                'folio' => 109,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE CANCHA DE FUTBOL RAPIDO',
                'project_place' => 'EJ. EL VERGEL',
                'viability' => true,
            ],
            [
                'folio' => 110,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE PLAZA PRINCIPAL',
                'project_place' => 'EJ. EL VERGEL',
                'viability' => true,
            ],
            [
                'folio' => 113,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACIÓN DE PLAZA',
                'project_place' => 'COL. AMPLIACIÓN LAZARO CARDENAS',
                'viability' => true,
            ],
            [
                'folio' => 114,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE CANCHA DE FUTBOL  CON PASTO SINTETICO',
                'project_place' => 'LOC. LA POPULAR',
                'viability' => true,
            ],
            [
                'folio' => 115,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE PLAZA EN LA LOCALIDAD',
                'project_place' => 'LOC. DOLORES',
                'viability' => true,
            ],
            [
                'folio' => 116,
                'assigned_district' => 11,
                'project_name' => 'INSTALACION DE TECHUMBRE',
                'project_place' => '15 DE DICIEMBRE',
                'viability' => true,
            ],
            [
                'folio' => 118,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE CANCHA Y BAÑOS EN E.S.T. NO. 78 LAZARO CARDENAS DEL RIO',
                'project_place' => 'LOC. SEIS DE OCTUBRE',
                'viability' => true,
            ],
            [
                'folio' => 119,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE PLAZA',
                'project_place' => 'LOC. ESTABLO MADRID',
                'viability' => true,
            ],
            [
                'folio' => 120,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE PLAZA, CANCHA Y TECHUMBRE',
                'project_place' => 'LOC. LA FORTUNA',
                'viability' => true,
            ],
            [
                'folio' => 121,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE CANCHA',
                'project_place' => 'LOC. PROVIDENCIA',
                'viability' => true,
            ],
            [
                'folio' => 122,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE CANCHA',
                'project_place' => 'LOC. PENJAMO',
                'viability' => true,
            ],
            [
                'folio' => 123,
                'assigned_district' => 11,
                'project_name' => 'SUMINISTRO Y COLOCACION DE PASTO SINTETICO EN CANCHA DE FUTBOL',
                'project_place' => 'COL. FILADELFIA',
                'viability' => true,
            ],
            [
                'folio' => 126,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE CANCHA Y SUMINISTRO DE EQUIPAMIENTO EN PLAZA',
                'project_place' => 'LOC. CHIUAHITA VIEJO',
                'viability' => true,
            ],
            [
                'folio' => 127,
                'assigned_district' => 12,
                'project_name' => 'CONSTRUCCION DE MALLA SOMBRA EN TEATRO DEL PUEBLO',
                'project_place' => 'FRAC. SANTA ROSA',
                'viability' => true,
            ],
            [
                'folio' => 128,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE PARADEROS DE AUTOBUS',
                'project_place' => 'LOC. ESTACIÓN VIÑEDO',
                'viability' => true,
            ],
            [
                'folio' => 129,
                'assigned_district' => 11,
                'project_name' => 'REHABILITACION DE CENTRO COMUNITARIO SOLIDARIDAD',
                'project_place' => 'COL. SOLIDARIDAD',
                'viability' => true,
            ],
            [
                'folio' => 130,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE PLAZA',
                'project_place' => 'LOC. VICENTE NAVA',
                'viability' => true,
            ],
            [
                'folio' => 131,
                'assigned_district' => 11,
                'project_name' => 'REHABILITACIÓN EN ESC. SEC. ESTATAL PROF. RAFAEL RAMIREZ CASTAÑEDA',
                'project_place' => 'COL. OCTAVIANO RENDON',
                'viability' => true,
            ],
            [
                'folio' => 132,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE CANCHA Y PLAZA',
                'project_place' => 'COL. MIGUEL DE LA MADRID',
                'viability' => true,
            ],
            [
                'folio' => 133,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACION DE CANCHA',
                'project_place' => 'H. MAYAGOITIA',
                'viability' => true,
            ],
            [
                'folio' => 134,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACION DE PLAZA PUBLICA',
                'project_place' => 'COL. VILLA NÁPOLES',
                'viability' => true,
            ],
            [
                'folio' => 135,
                'assigned_district' => 11,
                'project_name' => 'REHABILITACION DE PLAZA PUBLICA',
                'project_place' => 'COL. NIÑOS HÉROES',
                'viability' => true,
            ],
            [
                'folio' => 136,
                'assigned_district' => 10,
                'project_name' => 'REHBILITACION DE PLAZA Y CONSTRUCCION DE KIOSCO',
                'project_place' => 'LOC. BUCARELI',
                'viability' => true,
            ],
            [
                'folio' => 137,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE KIOSCO Y REHABILITACION DE PLAZA',
                'project_place' => 'EJ. RINCONADA',
                'viability' => true,
            ],
            [
                'folio' => 138,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE CANCHA Y SUMINISTRO DE JUEGOS INFANTIL',
                'project_place' => 'LOC. REFORMA',
                'viability' => true,
            ],
            [
                'folio' => 140,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE TECHUMBRE',
                'project_place' => 'LOC. CANDIDO AGUILAR',
                'viability' => true,
            ],
            [
                'folio' => 141,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE PLAZA Y  TECHUMBRE',
                'project_place' => 'LOC. VENECIA',
                'viability' => true,
            ],
            [
                'folio' => 142,
                'assigned_district' => 11,
                'project_name' => 'ALUMBRADO  PARA EL NUCLEO UNIVERSITARIO DE LA UJED',
                'project_place' => 'COL. FILADELFIA',
                'viability' => true,
            ],
            [
                'folio' => 143,
                'assigned_district' => 11,
                'project_name' => 'MALLA SOMBRA PARA  ESTACIONAMIENTO FACSA',
                'project_place' => 'COL. REVOLUCIÓN',
                'viability' => true,
            ],
            [
                'folio' => 144,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE PLAZA PRINCIPAL',
                'project_place' => 'LOC. LÁZARO CÁRDENAS',
                'viability' => true,
            ],
            [
                'folio' => 145,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACION DE PARQUE Y MALLA SOMBRA EN ESTRUCTURAS',
                'project_place' => 'COL. RUBEN JARAMILLO',
                'viability' => true,
            ],
            [
                'folio' => 146,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACION DE CENTRO COMUNITARIO 14 DE NOVIEMBRE',
                'project_place' => 'COL. 14 DE NOVIEMBRE',
                'viability' => true,
            ],
            [
                'folio' => 147,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE TECHUMBRE Y SANITARIOS',
                'project_place' => 'LOC. LA FLOR',
                'viability' => true,
            ],
            [
                'folio' => 149,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCION DE CANCHA',
                'project_place' => 'LOC. LAS MASITAS',
                'viability' => true,
            ],
            [
                'folio' => 150,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACION DE CANCHA DE FUT DE PASTO SINTETICO',
                'project_place' => 'PARQUE LA ESPERANZA',
                'viability' => true,
            ],
            [
                'folio' => 151,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE PLAZA',
                'project_place' => 'LOC. JABONOSO',
                'viability' => true,
            ],
            [
                'folio' => 152,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE CANCHA',
                'project_place' => 'LOC. VALLE DE EUREKA',
                'viability' => true,
            ],
            [
                'folio' => 153,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACION DE PLAZA',
                'project_place' => 'COL. DEL BOSQUE',
                'viability' => true,
            ],
            [
                'folio' => 154,
                'assigned_district' => 10,
                'project_name' => 'REAHBILITACION DE CANCHA',
                'project_place' => 'LOC. ABISINA DINAMITA',
                'viability' => true,
            ],
            [
                'folio' => 155,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE TECHUMBRE Y DESCANSO EN PANTEON',
                'project_place' => 'LOC. SAN TOO',
                'viability' => true,
            ],
            [
                'folio' => 156,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE PARQUE',
                'project_place' => 'LOC. LA TEHUA',
                'viability' => true,
            ],
            [
                'folio' => 157,
                'assigned_district' => 12,
                'project_name' => 'INSTALACION DE PASTO SINTETICO EN CANCHA DE FUTBOL',
                'project_place' => 'DEPORTIVA SAN ANTONIO',
                'viability' => true,
            ],
            [
                'folio' => 158,
                'assigned_district' => 11,
                'project_name' => 'REHABILITACION DE CENTRO COMUNITARIO EL CENTENARIO',
                'project_place' => 'COL. EL CENTENARIO',
                'viability' => true,
            ],
            [
                'folio' => 159,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCIÓN DE CENTRO COMUNITARIO',
                'project_place' => 'LOC. NUEVO CASTILLO',
                'viability' => true,
            ],
            [
                'folio' => 161,
                'assigned_district' => 12,
                'project_name' => 'REHABILITACIÓN PARQUE DEL CIRCUITO ALMENDRO',
                'project_place' => 'FRACC. RINCON LAS GRANJAS',
                'viability' => true,
            ],
            [
                'folio' => 162,
                'assigned_district' => 11,
                'project_name' => 'RESCATE Y REHABILITACION DEL TEATRO MUTIFUNCIONAL',
                'project_place' => 'FRACC. CASTELLANOS',
                'viability' => true,
            ],
            [
                'folio' => 163,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE PLAZA',
                'project_place' => 'EJ. EL TRUNFO',
                'viability' => true,
            ],
            [
                'folio' => 165,
                'assigned_district' => 10,
                'project_name' => 'CONSTRUCCION DE TECHUMBRE Y REHABILITACION DE CANCHA',
                'project_place' => 'EJ. EL VOLADO',
                'viability' => true,
            ],
            [
                'folio' => 166,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACIÓN DE PLAZA',
                'project_place' => 'EJ. EL QUEMADO',
                'viability' => true,
            ],
            [
                'folio' => 167,
                'assigned_district' => 11,
                'project_name' => 'REHABILITACIÓN DE PLAZOLETA CASA FAYA',
                'project_place' => 'ZONA CENTRO',
                'viability' => true,
            ],
            [
                'folio' => 168,
                'assigned_district' => 10,
                'project_name' => 'REHABILITACION DE PLAZA',
                'project_place' => 'EJ. SANTA CRUZ LUJAN',
                'viability' => true,
            ],
            [
                'folio' => 169,
                'assigned_district' => 11,
                'project_name' => 'REHABILITACION DE CANCHA DE FUTBOL CON PASTO SINTETICO Y GRADAS (CANCHAS LUNA)',
                'project_place' => 'FRAC. FIDEL VELAZQUEZ',
                'viability' => true,
            ],
            [
                'folio' => 170,
                'assigned_district' => 10,
                'project_name' => 'PARADEROS PARA AUTOBUS',
                'project_place' => 'EJ. SAN FELIPE',
                'viability' => true,
            ],
            [
                'folio' => 111,
                'assigned_district' => 12,
                'project_name' => 'CONSTRUCCIÓN DE PLAZA BIOSALUDABLE',
                'project_place' => 'COL. TIERRA BLANCA',
                'viability' => true,
            ],
            [
                'folio' => 124,
                'assigned_district' => 11,
                'project_name' => 'REHABILITACION DE PLAZA',
                'project_place' => 'COL. MIRAVALLE',
                'viability' => true,
            ],
        ];

        $data = array_map(function ($project) {
            return [
                'folio' => $project['folio'],
                'assigned_district' => $project['assigned_district'],
                'project_name' => $project['project_name'],
                'project_place' => $project['project_place'],
                'viability' => $project['viability'],
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }, $projects);

        DB::table('projects')->insert($data);
    }
}